### ISSUE TITLE
Identifier table exhausted

### ISSUE THREAD

**Issue by lighth7015** [alexfru/dflat20#1]
```
[robert.butler@mc01 dflat20]$ smlrcc @mldflat.txt
Error in "dflat.h" (81:15)
Identifier table exhausted

Failed command 'smlrc -huge -Wall -nopp window.i window.asm'
```
Any ideas what's going on here?

**Comment by alexfru** [comment]
What about sections -1 and 0 of compilin.txt?

**Comment by lighth7015** [comment]
Oh, I suppose that's what happens when you work on software running on a net sleep loss. Drunk driving? What about coding while sleep-impaired? :p

Anyway, that fixed it! Thanks!
